import flash.display.InteractiveObject;
import flash.events.Event;
import flash.events.MouseEvent;
/**
 *  Event structure and defintions for the CLIK Button: 
 *  Valid types:
 *      PRESS - "buttonPress"
 *      CLICK - "buttonClick"
 *      DRAG_OVER - "dragOver"
 *      DRAG_OUT - "dragOut"
 *      RELEASE_OUTSIDE - "releaseOutside"
 */
intrinsic class scaleform.clik.events.ButtonEvent extends Event
{
	/** The index of the controller/mouse used to generate the event (applicable only for multi-mouse cursor environments). */
	public var controllerIdx : uint;
	/** The index of the button on the controller/mouse used to generate the event. */
	public var buttonIdx : uint;
	/** true if the event was generated by a keyboard/gamepad; false if the event was generated by a mouse. */
	public var isKeyboard : Boolean;
	/** true if the event was generated by an autoRepeating button being held down; false the button is not currently repeating. */
	public var isRepeat : Boolean;
	static public var PRESS : String;
	static public var CLICK : String;
	static public var DRAG_OVER : String;
	static public var DRAG_OUT : String;
	static public var RELEASE_OUTSIDE : String;

	public function ButtonEvent(type:String, bubbles:Boolean = true, cancelable:Boolean = false, controllerIdx:uint = 0, buttonIdx:uint = 0, isKeyboard:Boolean = false, isRepeat:Boolean = false);

	public function clone() : Event;

	public function toString() : String;

}