import flash.display.MovieClip;
import flash.events.Event;
import flash.text.TextField;
import scaleform.clik.constants.ScrollBarDirection;
import scaleform.clik.constants.InvalidationType;
import scaleform.clik.constants.InputValue;
import scaleform.clik.constants.NavigationCode;
import scaleform.clik.controls.Button;
import scaleform.clik.core.UIComponent;
import scaleform.clik.events.ComponentEvent;
import scaleform.clik.events.InputEvent;
import scaleform.clik.interfaces.IScrollBar;
import scaleform.clik.ui.InputDetails;
/**
 * The CLIK ScrollIndicator displays the scroll position of another component, such as a multiline textField. It can be pointed at a textField to automatically display its scroll position. All list-based components as well as the TextArea have a scrollBar property which can be pointed to a ScrollIndicator or ScrollBar instance or linkage ID. 
    
    <b>Inspectable Properties</b>
    The inspectable properties of the ScrollIndicator are:
    <ul>
        <li><i>scrollTarget</i>: Set a TextArea or normal multiline textField as the scroll target to automatically respond to scroll events. Non-text field types have to manually update the ScrollIndicator properties.</li>
        <li><i>visible</i>: Hides the component if set to false.</li>
        <li><i>enabled</i>: Disables the component if set to false.</li>
        <li><i>offsetTop</i>: Thumb offset at the top. A positive value moves the thumb's top-most position higher.</li>
        <li><i>offsetBottom</i>: Thumb offset at the bottom. A positive value moves the thumb's bottom-most position lower.</li>
    </ul>
    
    <b>States</b> 
    The ScrollIndicator does not have explicit states. It uses the states of its child elements, the thumb and track Button components.    
    
     <b>Events</b>
    All event callbacks receive a single Event parameter that contains relevant information about the event. The following properties are common to all events. <ul>
    <li><i>type</i>: The event type.</li>
    <li><i>target</i>: The target that generated the event.</li></ul>
        
    The events generated by the ScrollIndicator component are listed below. The properties listed next to the event are provided in addition to the common properties.
    <ul>
        <li><i>ComponentEvent.SHOW</i>: The visible property has been set to true at runtime.</li>
        <li><i>ComponentEvent.HIDE</i>: The visible property has been set to false at runtime.</li>
        <li><i>Event.SCROLL</i>: The scroll position has changed.</li>
    </ul>
 */
intrinsic class scaleform.clik.controls.ScrollIndicator extends UIComponent implements IScrollBar
{
	/** The direction of the scroll bar. Valid values are ScrollBarDirection.VERTICAL / ScrollBarDirection.HORIZONTAL. */
	public var direction : String;
	public var offsetTop : Number;
	public var offsetBottom : Number;
	public var _isDragging : Boolean;
	public var _maxPosition : Number;
	public var _minPosition : Number;
	public var _minThumbSize : Number;
	public var _pageScrollSize : Number;
	public var _pageSize : Number;
	public var _position : Number;
	public var _scrollTarget : Object;
	/** A reference to the thumb symbol in the ScrollIndicator. */
	public var thumb : MovieClip;
	/** A reference to the track symbol in the ScrollIndicator. */
	public var track : MovieClip;

	public function get enabled() : Boolean;
	public function set enabled(value:Boolean) : void;

	/**
         * The current position of the ScrollIndicator.
         */
	public function get position() : Number;
	public function set position(value:Number) : void;

	public function get minThumbSize() : Number;
	public function set minThumbSize(value:Number) : void;

	public function get isHorizontal() : Boolean;

	public function get scrollTarget() : Object;
	public function set scrollTarget(value:Object) : void;

	/**
         * Returns the available scrolling height of the component.
         */
	public function get availableHeight() : Number;


	public function ScrollIndicator();

	public function initialize() : void;

	/**
         * Set the scroll properties of the component.
         * @param pageSize The size of the pages to determine scroll distance.
         * @param minPosition The minimum scroll position.
         * @param maxPosition The maximum scroll position.
         * @param pageScrollSize The amount to scroll when "paging". Not currently implemented.
         */
	public function setScrollProperties(pageSize:Number, minPosition:Number, maxPosition:Number, pageScrollSize:Number = NaN) : void;

	/** @exclude */
	public function handleInput(event:InputEvent) : void;

	/** @exclude */
	public function toString() : String;

	public function configUI() : void;

	public function draw() : void;

	public function drawLayout() : void;

	public function updateThumb() : void;

	public function updateThumbPosition() : void;

	public function handleTargetScroll(event:Event) : void;

}