import flash.display.MovieClip;
import flash.events.Event;
import flash.events.MouseEvent;
import flash.geom.Point;
import flash.text.TextField;
import scaleform.clik.constants.ScrollBarTrackMode;
import scaleform.clik.constants.InvalidationType;
import scaleform.clik.core.UIComponent;
import scaleform.clik.events.ButtonEvent;
import scaleform.clik.events.InputEvent;
import scaleform.clik.events.ComponentEvent;
import scaleform.clik.utils.Constraints;
import scaleform.clik.constants.ConstrainMode;
import scaleform.clik.constants.ScrollBarDirection;
/**
 *  The CLIK ScrollBar displays and controls the scroll position of another component. It adds interactivity to the ScrollIndicator with a draggable thumb button, as well as optional “up” and “down” arrow buttons, and a clickable track. 
    
    <b>Inspectable Properties</b>
    The inspectable properties of the ScrollBar are similar to ScrollIndicator with one addition:
    <ul>
        <li><i>enabled</i>: Disables the component if set to false.</li>
        <li><i>offsetTop</i>: Thumb offset at the top. A positive value moves the thumb's top-most position higher.</li>
        <li><i>offsetBottom</i>: Thumb offset at the bottom. A positive value moves the thumb's bottom-most position lower.</li>
        <li><i>trackMode</i>: When the user clicks on the track with the cursor, the scrollPage setting will cause the thumb to continuously scroll by a page until the cursor is released. The scrollToCursor setting will cause the thumb to immediately jump to the cursor and will also transition the thumb into a dragging mode until the cursor is released.</li>
        <li><i>scrollTarget</i>: Set a TextArea or normal multiline textField as the scroll target to automatically respond to scroll events. Non-text field types have to manually update the ScrollIndicator properties.</li>
        <li><i>visible</i>: Hides the component if set to false.</li>
    </ul>
    
    <b>States</b>
    The ScrollBar, similar to the ScrollIndicator, does not have explicit states. It uses the states of its child elements, the thumb, up, down and track Button components.
    
    
    <b>Events</b>
    All event callbacks receive a single Event parameter that contains relevant information about the event. The following properties are common to all events. <ul>
    <li><i>type</i>: The event type.</li>
    <li><i>target</i>: The target that generated the event.</li></ul>
        
    The events generated by the ScrollBar component are listed below. The properties listed next to the event are provided in addition to the common properties.
    <ul>
        <li><i>ComponentEvent.SHOW</i>: The visible property has been set to true at runtime.</li>
        <li><i>ComponentEvent.HIDE</i>: The visible property has been set to false at runtime.</li>
        <li><i>Event.SCROLL</i>: The scroll position has changed.</li>
    </ul>
*/
intrinsic class scaleform.clik.controls.ScrollBar extends ScrollIndicator
{
	public var trackScrollPageSize : Number;
	public var _dragOffset : Point;
	public var _trackMode : String;
	public var _trackScrollPosition : Number;
	public var _trackDragMouseIndex : Number;
	/** A reference to the up arrow symbol in the ScrollBar, used to decrement the scroll position. */
	public var upArrow : Button;
	/** A reference to the down arrow symbol in the ScrollBar, used to increment the scroll position. */
	public var downArrow : Button;

	public function get enabled() : Boolean;
	public function set enabled(value:Boolean) : void;

	/** 
         * Set the scroll position to a number between the minimum and maximum.
         */
	public function get position() : Number;
	public function set position(value:Number) : void;

	public function get trackMode() : String;
	public function set trackMode(value:String) : void;

	/** @exclude */
	public function get availableHeight() : Number;


	public function ScrollBar();

	public function initialize() : void;

	public function preInitialize() : void;

	/** @exclude */
	public function toString() : String;

	public function configUI() : void;

	public function scrollUp() : void;

	public function scrollDown() : void;

	public function drawLayout() : void;

	public function updateThumb() : void;

	public function updateThumbPosition() : void;

	public function handleUpArrowClick(event:ButtonEvent) : void;

	public function handleUpArrowPress(event:ButtonEvent) : void;

	public function handleDownArrowClick(event:ButtonEvent) : void;

	public function handleDownArrowPress(event:ButtonEvent) : void;

	public function handleThumbPress(event:Event) : void;

	public function doDrag(event:MouseEvent) : void;

	public function endDrag(event:MouseEvent) : void;

	public function handleTrackPress(event:MouseEvent) : void;

	public function handleTrackClick(event:ButtonEvent) : void;

	public function updateScrollTarget() : void;

	public function handleMouseWheel(event:MouseEvent) : void;

	public function changeFocus() : void;

}