/**
 * An InputDetails object is generated by the InputDelegate, and contains relevant information about user input, such as controller buttons, keyboard keys, etc.
 */
intrinsic class scaleform.clik.ui.InputDetails
{
	public var type : String;
	public var code : Number;
	public var value : Object;
	public var navEquivalent : String;
	public var controllerIndex : uint;
	public var ctrlKey : Boolean;
	public var altKey : Boolean;
	public var shiftKey : Boolean;

	public function InputDetails(type:String, code:Number, value:*, navEquivalent:String = null, controllerIndex:uint = 0, ctrlKey:Boolean = false, altKey:Boolean = false, shiftKey:Boolean = false);

	public function toString() : String;

}